export type Locale = "ar" | "en";
export const locales: Locale[] = ["ar", "en"];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);

// Edit personal details here. Use international digits only for WhatsApp.
// Leave missing values empty: the UI never creates a fake contact link.
export const profile = {
  name: { ar: "عمر الديك", en: "Omar Aldeek" },
  whatsapp: "",
  email: "",
  siteUrl: "", // Your real production origin, e.g. https://your-domain.com
  location: { ar: "من فلسطين، إلى كل مكان", en: "From Palestine, to everywhere" },
};

export const copy = {
  ar: {
    title: "عمر الديك — تصميم وتطوير مواقع بطابع مختلف",
    description: "تصميم وتطوير مواقع وصفحات هبوط تجمع الجمال والوضوح. عمر الديك، مصمم ومطور مواقع مستقل من فلسطين.",
    nav: ["الأعمال", "الخدمات", "طريقة العمل", "التواصل"],
    skip: "انتقل إلى المحتوى", menu: "فتح القائمة", close: "إغلاق القائمة", navigation: "التنقل الرئيسي",
    role: "مصمم ومطوّر مواقع مستقل", heroEyebrow: "فكرة واضحة. حضور يستحقها.",
    heroLines: ["حضورٌ يُلفت.", "وتجربةٌ تُقنع."],
    heroText: "أصمّم وأطوّر مواقع تُظهر قيمة مشروعك؛ جميلة في تفاصيلها، واضحة في رسالتها، وسهلة في استخدامها.",
    featured: "من معرض الأعمال", featuredName: "فورما — تجربة لاستوديو تصميم داخلي", cinematicAlt: "صورة مرجعية لمساحة داخلية من التصور التصميمي لفورما",
    workEdition: "دراسات في التصميم والتطوير", servicesStatement: "مواقع للعمل.\nبتفكير مصمّم.",
    aboutStatement: "تفاصيل رقمية.\nبلمسة شخصية.", collaborationLabel: "ثلاث طرق لنبدأ", contactKicker: "كل مشروع مميز يبدأ بحديث",
    discuss: "ناقش مشروعك", explore: "استكشف الأعمال", scroll: "تصفّح على مهل", heroCaption: "أفكار تتحوّل إلى تجارب رقمية",
    heroNote: "معاينات من نماذجي التجريبية", discipline: ["تصميم مدروس", "تطوير متقن", "تفاصيل تصنع الفرق"],
    workLabel: "01 / الأعمال", workTitle: "أعمال تُرى.\nوأفكار تُحسّ.",
    workIntro: "ثلاث أفكار، وثلاث تجارب مختلفة. مساحة لاستكشاف ما يمكن أن يكون عليه موقعك القادم.",
    concept: "نموذج تجريبي — ليس مشروع عميل", viewProject: "اكتشف المشروع", viewAll: "استكشف جميع الأعمال",
    servicesLabel: "02 / الخدمات", servicesTitle: "الفكرة لك.\nوالتفاصيل عليّ.",
    servicesIntro: "حلول واضحة لحضور رقمي يخدم مشروعك، ويشبهك.",
    services: [
      { title: "تصميم وتطوير المواقع", text: "موقع يعبّر عن هوية مشروعك، يرتّب معلوماته بوضوح، ويمنح زوارك تجربة مريحة على كل شاشة.", tags: ["تصميم مخصص", "تجربة متجاوبة", "تطوير واجهات"] },
      { title: "صفحات الهبوط", text: "صفحة مركّزة لحملة أو منتج أو خدمة. رسالة واضحة ومسار بسيط يقود الزائر إلى الخطوة التالية.", tags: ["رسالة مركّزة", "دعوة واضحة للتواصل"] },
      { title: "الصيانة والتحديثات", text: "مواكبة احتياجات موقعك بعد الإطلاق؛ من تحديث المحتوى إلى إصلاح المشاكل وتحسين تجربة الاستخدام.", tags: ["تحديث المحتوى", "متابعة تقنية"] },
    ],
    processLabel: "03 / طريقة العمل", processTitle: "من الفكرة،\nإلى الواجهة.",
    processIntro: "تعرف أين وصلنا، وما الذي يأتي بعد ذلك. تواصل مباشر وقرارات نأخذها معًا.",
    steps: [
      { title: "نفهم المشروع", text: "نتحدث عن فكرتك، جمهورك، وما تريد أن يحققه الموقع. ونحدد نطاق العمل بوضوح." },
      { title: "نضع الاتجاه", text: "نرتّب المحتوى ونختار اللغة البصرية المناسبة، قبل الدخول في التفاصيل." },
      { title: "نصمّم ونطوّر", text: "نحوّل الاتجاه إلى تجربة فعلية، ونراجعها معك على الكمبيوتر والهاتف." },
      { title: "نطلق ونتابع", text: "نفحص التفاصيل، نجهّز الإطلاق، ونتفق على ما تحتاجه من متابعة وتحديثات." },
    ],
    noteLabel: "ملاحظة شخصية", designNote: "لا أبدأ بالألوان.\nأبدأ بفهم ما تريد قوله.", processFootnote: "من الفكرة إلى الإطلاق، خطوة بخطوة.",
    aboutLabel: "قليل عنّي", aboutTitle: "أهلاً، أنا عمر.",
    aboutText: "مصمم ومطوّر مواقع مستقل من فلسطين. أحب المواقع التي توازن بين الفكرة الجميلة والتفاصيل العملية. أعمل معك مباشرة لأفهم مشروعك، وأبني له حضورًا واضحًا يشبهه.",
    aboutNote: "أؤمن أن الموقع الجيد يبدأ بالاستماع.",
    optionsLabel: "04 / التعاون", optionsTitle: "مساحة لمشروعك القادم.", quote: "اطلب عرض سعر",
    options: [
      { title: "موقع تعريفي", text: "لتقديم مشروعك وخدماتك بوضوح.", items: ["هيكلة المحتوى والصفحات", "تصميم متجاوب", "وسائل تواصل واضحة"], price: null as string | null },
      { title: "موقع أعمال مخصص", text: "لتجربة أوسع لها متطلباتها الخاصة.", items: ["اتجاه بصري مخصص", "صفحات وتجارب حسب النطاق", "تهيئة أساسية لمحركات البحث"], price: null as string | null },
      { title: "صيانة وتحديثات", text: "لموقع قائم يحتاج إلى اهتمام مستمر.", items: ["مراجعة احتياجات الموقع", "تحديثات متفق عليها", "إصلاحات وتحسينات"], price: null as string | null },
    ],
    optionsNote: "النطاق والتكلفة والمدة تُحدّد حسب المشروع. الدومين والاستضافة يُناقشان بشكل مستقل.",
    faqLabel: "قبل أن نبدأ", faqTitle: "ربما تتساءل…",
    faq: [
      { q: "ماذا أحتاج قبل بدء المشروع؟", a: "فكرة عن هدف الموقع وجمهوره، وأي مواد متوفرة مثل الشعار والنصوص والصور. إذا لم يكن المحتوى جاهزًا، نحدّد معًا ما يلزم تجهيزه ومسؤولية كل طرف." },
      { q: "كم يستغرق تصميم وتطوير الموقع؟", a: "يعتمد ذلك على عدد الصفحات والتفاصيل المطلوبة وجاهزية المحتوى. بعد فهم المشروع نضع جدولًا واقعيًا، ونوضّح أثر أي تغييرات على موعد التسليم." },
      { q: "كيف تتم المراجعات والتعديلات؟", a: "نحدّد مراحل المراجعة وعدد جولات التعديل ضمن عرض العمل. أي طلب يضيف إلى النطاق المتفق عليه نناقش أثره على التكلفة والمدة قبل تنفيذه." },
      { q: "هل يمكن متابعة الموقع بعد الإطلاق؟", a: "نعم، يمكن الاتفاق على صيانة وتحديثات حسب حاجة الموقع. يشمل الاتفاق المهام المطلوبة وآلية التواصل، ولا تُضاف خدمة متابعة تلقائيًا دون اتفاق." },
      { q: "هل الدومين والاستضافة مشمولان؟", a: "ليسا مشمولين تلقائيًا. نناقش الخيارات المناسبة، وتُذكر تكلفتهما وملكيتهما بوضوح ضمن الاتفاق." },
    ],
    contactLabel: "الفكرة التالية قد تكون فكرتك", contactTitle: "لنصنع حضورًا\nيليق بمشروعك.",
    contactText: "لديك فكرة، أو موقع يحتاج إلى بداية جديدة؟ لنبدأ بحديث بسيط.",
    whatsapp: "تواصل عبر واتساب", email: "أرسل بريدًا", pendingContact: "بيانات التواصل ستُضاف قريبًا. يمكنك الآن تجهيز موجز مشروعك والاحتفاظ به.",
    prepare: "جهّز موجز مشروعك", briefTitle: "لنرتّب فكرتك.", briefHelp: "هذا الموجز يُحفظ على جهازك فقط، ولا يُرسل إلى أي جهة.",
    nameLabel: "اسمك أو اسم المشروع", ideaLabel: "ماذا تريد أن نبني؟", briefSubmit: "حمّل موجز المشروع", briefError: "أدخل الاسم ووصفًا لا يقل عن 10 أحرف.",
    briefDone: "تم تجهيز ملف الموجز للتحميل. لم يتم إرسال أي بيانات.",
    briefNeedsJS: "يتطلب حفظ الموجز محليًا تشغيل JavaScript. الحقول معطّلة حاليًا، ولن تُرسل أي بيانات.",
    footerNote: "صُنع بفكرة، وعناية بالتفاصيل.", backTop: "إلى الأعلى", rights: "جميع الحقوق محفوظة",
    backWork: "العودة إلى الأعمال", goal: "الهدف", solution: "الحل التصميمي", delivered: "الأجزاء المنفذة", preview: "المعاينة", openPreview: "افتح المعاينة المحلية", nextProject: "المشروع التالي", projectDetails: "عن المشروع", previewNotice: "هذه معاينة تصميمية محلية. العلامة والمحتوى توضيحيان، ولا يوجد نشاط تجاري أو حجز أو شراء فعلي.", backProject: "العودة إلى تفاصيل المشروع",
  },
  en: {
    title: "Omar Aldeek — Thoughtful websites, distinct identities",
    description: "Independent web design and development from Palestine. Thoughtful websites and landing pages that bring clarity and character to your business.",
    nav: ["Work", "Services", "Process", "Contact"],
    skip: "Skip to content", menu: "Open menu", close: "Close menu", navigation: "Main navigation",
    role: "Independent designer & developer", heroEyebrow: "A clear idea. A presence to match.",
    heroLines: ["Made to stand out.", "Built to feel right."],
    heroText: "I design and develop websites that express the value of your business. Considered in every detail, clear in their message, and effortless to use.",
    featured: "From the collection", featuredName: "Forma — an interior studio experience", cinematicAlt: "Interior reference photography from the Forma design concept",
    workEdition: "Studies in design and development", servicesStatement: "Built for business.\nLed by design.",
    aboutStatement: "Digital craft.\nA personal touch.", collaborationLabel: "Three ways to begin", contactKicker: "Every considered project starts with a conversation",
    discuss: "Let's talk", explore: "Explore the work", scroll: "Take your time. Scroll.", heroCaption: "Ideas, made into digital experiences",
    heroNote: "A selection of my design concepts", discipline: ["Thoughtful design", "Careful development", "Details that matter"],
    workLabel: "01 / Selected work", workTitle: "Work you see.\nIdeas you feel.",
    workIntro: "Three ideas. Three different experiences. A space to explore what your next website could look like.",
    concept: "Design concept — not a client project", viewProject: "Discover project", viewAll: "Explore all work",
    servicesLabel: "02 / Services", servicesTitle: "Your idea.\nEvery detail, considered.",
    servicesIntro: "Clear solutions for a digital presence that serves your business and feels like you.",
    services: [
      { title: "Web design & development", text: "A website that reflects your identity, brings clarity to your content, and feels easy to use on every screen.", tags: ["Custom design", "Responsive experience", "Frontend development"] },
      { title: "Landing pages", text: "A focused page for a campaign, product, or service. A clear message and a simple path to the next step.", tags: ["Focused messaging", "Clear calls to action"] },
      { title: "Maintenance & updates", text: "Care for your website beyond launch, from content updates and fixes to improvements in everyday usability.", tags: ["Content updates", "Technical support"] },
    ],
    processLabel: "03 / The process", processTitle: "From the idea\nto the experience.",
    processIntro: "Know where we are and what comes next. Direct communication and decisions we make together.",
    steps: [
      { title: "Understand", text: "We talk about your idea, audience, and what the website should achieve. Then we define a clear scope." },
      { title: "Find the direction", text: "We organise the content and establish the visual language before exploring the details." },
      { title: "Design & build", text: "We turn the direction into a working experience and review it together on desktop and mobile." },
      { title: "Launch & support", text: "We check the details, prepare for launch, and agree on the updates and support you need." },
    ],
    noteLabel: "A personal note", designNote: "Before the colours,\nI listen to the idea.", processFootnote: "From the idea to launch, one step at a time.",
    aboutLabel: "The person behind the pixels", aboutTitle: "Hi, I'm Omar.",
    aboutText: "An independent web designer and developer from Palestine. I like websites that balance a thoughtful idea with practical details. I work with you directly to understand your business and build a clear presence that feels like it.",
    aboutNote: "I believe a good website starts with listening.",
    optionsLabel: "04 / Collaboration", optionsTitle: "Room for your next idea.", quote: "Request a quote",
    options: [
      { title: "Business website", text: "A clear introduction to your business and services.", items: ["Content and page structure", "Responsive design", "Clear contact pathways"], price: null as string | null },
      { title: "Custom website", text: "A broader experience with its own requirements.", items: ["A distinct visual direction", "Pages and interactions to scope", "Foundational search optimisation"], price: null as string | null },
      { title: "Maintenance & updates", text: "Ongoing attention for an existing website.", items: ["A review of your site's needs", "Agreed content updates", "Fixes and improvements"], price: null as string | null },
    ],
    optionsNote: "Scope, cost and timeline are tailored to the project. Domain and hosting are discussed separately.",
    faqLabel: "Before we begin", faqTitle: "You might be wondering…",
    faq: [
      { q: "What do I need before we start?", a: "An idea of your goals and audience, plus any existing materials such as your logo, copy and photos. If content isn't ready, we identify what is needed and who will prepare it." },
      { q: "How long does a website take?", a: "It depends on the pages, features and content readiness. Once the scope is clear, we set a realistic timeline and discuss how any changes affect delivery." },
      { q: "How do reviews and revisions work?", a: "Review stages and revision rounds are defined in the proposal. If a request adds to the agreed scope, we discuss its effect on budget and timing before going ahead." },
      { q: "Can you help after launch?", a: "Yes. We can agree on maintenance and updates based on your site's needs, including the tasks and communication process. Ongoing support is never added without an agreement." },
      { q: "Are domain and hosting included?", a: "They aren't automatically included. We discuss suitable options and clearly document their cost and ownership in the agreement." },
    ],
    contactLabel: "The next idea could be yours", contactTitle: "Let's make a presence\nworthy of your business.",
    contactText: "Have an idea, or a website ready for a fresh start? Let's begin with a simple conversation.",
    whatsapp: "Chat on WhatsApp", email: "Send an email", pendingContact: "Contact details will be added soon. For now, you can prepare a project brief and keep a copy.",
    prepare: "Prepare your project brief", briefTitle: "Let's shape your idea.", briefHelp: "This brief is saved on your device only. It isn't sent anywhere.",
    nameLabel: "Your name or project name", ideaLabel: "What would you like to build?", briefSubmit: "Download project brief", briefError: "Add a name and a description of at least 10 characters.",
    briefDone: "Your brief is ready to download. No information has been sent.",
    briefNeedsJS: "Saving a brief locally requires JavaScript. The fields are disabled and no information will be sent.",
    footerNote: "Made with intention. Built with care.", backTop: "Back to top", rights: "All rights reserved",
    backWork: "Back to work", goal: "The goal", solution: "Design approach", delivered: "What was built", preview: "Preview", openPreview: "Open local preview", nextProject: "Next project", projectDetails: "About the project", previewNotice: "A local design concept. The brand and content are illustrative; no real business, booking or purchase is available.", backProject: "Back to project details",
  },
};

export const projects = [
  {
    slug: "finjan", number: "01", theme: "coffee", label: "FINJAN", year: "2026",
    ar: { name: "فنجان", type: "موقع مقهى مختص", summary: "مساحة رقمية دافئة، تشبه أول رشفة قهوة في صباح هادئ.", goal: "استكشاف حضور رقمي لمقهى مختص يروي قصة المكان ويقدّم منتجاته في تجربة سهلة.", solution: "درجات بنية وكريمية، عناوين واسعة وصور قريبة من تفاصيل القهوة. تكوين يترك مساحة للحكاية والمنتج معًا.", parts: ["صفحة افتتاحية متجاوبة", "عرض توضيحي لقائمة القهوة", "قسم قصة المقهى", "تجربة عربية وإنجليزية"], tags: ["تصميم واجهات", "تطوير", "مقهى"] },
    en: { name: "Finjan", type: "Specialty coffee website", summary: "A warm digital space, like the first sip of coffee on a quiet morning.", goal: "Explore a digital home for a specialty café, bringing its story and coffee into one easy experience.", solution: "Coffee brown and cream, generous type, and close-up coffee photography. A composition that gives both the story and the product room to breathe.", parts: ["Responsive homepage", "Illustrative coffee menu", "Café story section", "Arabic and English experience"], tags: ["UI design", "Development", "Coffee"] },
  },
  {
    slug: "forma", number: "02", theme: "interior", label: "FORMA", year: "2026",
    ar: { name: "فورما", type: "استوديو تصميم داخلي", summary: "حين تصبح المساحة لغة. تجربة هادئة تترك التصميم يتحدث.", goal: "إنشاء تصور لمعرض معماري يعطي المساحات والصور أولوية، مع تعريف واضح بفلسفة الاستوديو.", solution: "شبكة تحريرية، ألوان حجرية، وتوازن بين الصور الكبيرة والهوامش. عناوين بسيطة ترافق المعاينات دون أن تزاحمها.", parts: ["واجهة معرض معماري", "عرض أعمال بصري", "قسم فلسفة التصميم", "تخطيط متجاوب باللغتين"], tags: ["اتجاه فني", "تصميم واجهات", "تطوير"] },
    en: { name: "Forma", type: "Interior design studio", summary: "When space becomes a language. A quiet experience that lets design speak.", goal: "Create an architectural portfolio concept that gives space and imagery priority while clearly expressing a studio's philosophy.", solution: "An editorial grid, stone tones, and a balance of large images and generous margins. Restrained headlines accompany the work without competing with it.", parts: ["Architectural portfolio interface", "Visual project showcase", "Design philosophy section", "Bilingual responsive layouts"], tags: ["Art direction", "UI design", "Development"] },
  },
  {
    slug: "madar", number: "03", theme: "business", label: "MADAR", year: "2026",
    ar: { name: "مدار", type: "موقع شركة خدمات", summary: "فكرة مؤسسية أكثر إنسانية. وضوح يمنح العمل مساحة للنمو.", goal: "تصوّر موقع لشركة خدمات يجعل فهم عرضها والتنقل بين معلوماتها بسيطًا لأصحاب المشاريع.", solution: "أزرق عميق مع مساحات فاتحة وشبكة هندسية واضحة. التسلسل البصري يشرح الفكرة ثم يوجّه نحو تفاصيل الخدمات.", parts: ["صفحة تعريف بالشركة", "عرض منظم للخدمات", "قسم منهجية العمل", "واجهات مهيأة للهاتف"], tags: ["تصميم مواقع", "تطوير", "أعمال"] },
    en: { name: "Madar", type: "Business services website", summary: "A more human business presence. Clarity that gives ideas room to grow.", goal: "Imagine a service company's website that makes its offer and information easy for business owners to understand.", solution: "Deep blue, light surfaces and a clear geometric grid. A visual hierarchy introduces the idea before guiding visitors into the services.", parts: ["Company introduction page", "Structured service overview", "Process section", "Mobile-ready interfaces"], tags: ["Web design", "Development", "Business"] },
  },
];
export type Project = (typeof projects)[number];
